# Chapter: 6
## Section: Counterfactual generation using DiCE

In [1]:
!pip install shap
!pip install dice_ml

Installing collected packages: raiutils, dice_ml
Successfully installed dice_ml-0.10 raiutils-0.4.0

In [2]:
###### This example is taken from https://github.com/interpretml/DiCE ########
import dice_ml
from dice_ml.utils import helpers # helper functions
from sklearn.model_selection import train_test_split

dataset = helpers.load_adult_income_dataset()
target = dataset["income"] # outcome variable
train_dataset, test_dataset, _, _ = train_test_split(dataset,
                                                     target,
                                                     test_size=0.2,
                                                     random_state=0,
                                                     stratify=target)
# Dataset for training an ML model
d = dice_ml.Data(dataframe=train_dataset,
                 continuous_features=['age', 'hours_per_week'],
                 outcome_name='income')

# Pre-trained ML model
m = dice_ml.Model(model_path=dice_ml.utils.helpers.get_adult_income_modelpath(),
                  backend='TF2', func="ohe-min-max")
# DiCE explanation instance
exp = dice_ml.Dice(d,m)

/usr/local/lib/python3.10/dist-packages/dice_ml/utils/exception.py:12: UserWarning: UserConfigValidationException will be deprecated from dice_ml.utils. Please import UserConfigValidationException from raiutils.exceptions.
  warnings.warn("UserConfigValidationException will be deprecated from dice_ml.utils. "

In [3]:
import dice_ml
from dice_ml.utils import helpers # helper functions

# Generate counterfactual examples
query_instance = test_dataset.drop(columns="income")[0:1]
dice_exp = exp.generate_counterfactuals(query_instance, total_CFs=10, desired_class="opposite", random_seed = 42)
# Visualize counterfactual explanation
dice_exp.visualize_as_dataframe()

100%|██████████| 1/1 [00:05<00:00,  5.91s/it]

Query instance (original outcome : 0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,29,Private,HS-grad,Married,Blue-Collar,White,Female,38,0

Diverse Counterfactual set (new outcome: 1.0)

,age,workclass,education,marital_status,occupation,race,gender,hours_per_week,income
0,80.0,Private,HS-grad,Married,Service,White,Female,38,1
1,29.0,Private,HS-grad,Married,Blue-Collar,White,Female,97.0,1
2,29,Private,HS-grad,Married,Service,White,Female,92.0,1
3,29,Private,HS-grad,Married,Blue-Collar,White,Female,93.0,1
4,29,Private,Assoc,Married,Blue-Collar,White,Female,59.0,1
5,49.0,Private,HS-grad,Married,Blue-Collar,White,Female,72.0,1
6,29,Private,Assoc,Married,Service,White,Female,38,1
7,29,Private,HS-grad,Married,Blue-Collar,Other,Female,97.0,1
8,90.0,Private,Doctorate,Married,Blue-Collar,White,Female,38,1
9,58.0,Private,HS-grad,Married,Blue-Collar,White,Female,76.0,1